### ISSUE TITLE
Node Project fails to build

### ISSUE THREAD

**Issue by brianrandell** [DarqueWarrior/generator-vsts#7]
Run YO VSTS to create a Node application.
Use Hosted build.
Push changes to VSTS.
Build fails.
npm failed with error: C:\Program Files\nodejs\npm.cmd failed with return code: 1

**Comment by brianrandell** [comment]
More error details from log:

2016-12-05T07:50:52.5257529Z C:\a\1\s\node_modules\selenium-webdriver\index.js:115
2016-12-05T07:50:52.5267522Z   static createSession(...args) {}
2016-12-05T07:50:52.5267522Z                        ^^^
2016-12-05T07:50:52.5267522Z 
2016-12-05T07:50:52.5267522Z SyntaxError: Unexpected token ...
2016-12-05T07:50:52.5267522Z     at exports.runInThisContext (vm.js:53:16)
2016-12-05T07:50:52.5267522Z     at Module._compile (module.js:387:25)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-05T07:50:52.5267522Z     at Module.load (module.js:357:32)
2016-12-05T07:50:52.5267522Z     at Function.Module._load (module.js:314:12)
2016-12-05T07:50:52.5267522Z     at Module.require (module.js:367:17)
2016-12-05T07:50:52.5267522Z     at require (internal/module.js:20:19)
2016-12-05T07:50:52.5267522Z     at Object.<anonymous> (C:\a\1\s\test\uiTest.js:2:19)
2016-12-05T07:50:52.5267522Z     at Module._compile (module.js:413:34)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-05T07:50:52.5267522Z     at Module.load (module.js:357:32)
2016-12-05T07:50:52.5267522Z     at Function.Module._load (module.js:314:12)
2016-12-05T07:50:52.5267522Z     at Module.require (module.js:367:17)
2016-12-05T07:50:52.5267522Z     at require (internal/module.js:20:19)
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\mocha\lib\mocha.js:222:27
2016-12-05T07:50:52.5267522Z     at Array.forEach (native)
2016-12-05T07:50:52.5267522Z     at Mocha.loadFiles (C:\a\1\s\node_modules\mocha\lib\mocha.js:219:14)
2016-12-05T07:50:52.5267522Z     at Mocha.run (C:\a\1\s\node_modules\mocha\lib\mocha.js:487:10)
2016-12-05T07:50:52.5267522Z     at Object.<anonymous> (C:\a\1\s\node_modules\mocha\bin\_mocha:459:18)
2016-12-05T07:50:52.5267522Z     at Module._compile (module.js:413:34)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-05T07:50:52.5267522Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-05T07:50:52.5267522Z     at Module.load (module.js:357:32)
2016-12-05T07:50:52.5267522Z     at Function.Module._load (module.js:314:12)
2016-12-05T07:50:52.5267522Z     at Function.Module.runMain (module.js:447:10)
2016-12-05T07:50:52.5267522Z     at runFn (C:\a\1\s\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\lib\util\file-matcher.js:68:16
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:52:16
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:361:13
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:52:16
2016-12-05T07:50:52.5267522Z     at done (C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:246:17)
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:44:16
2016-12-05T07:50:52.5267522Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:358:17
2016-12-05T07:50:52.5267522Z     at LOOP (fs.js:1609:14)
2016-12-05T07:50:52.5267522Z     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-12-05T07:50:52.5267522Z     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-05T07:50:52.5407526Z npm ERR! Test failed.  See above for more details.
2016-12-05T07:50:52.5577517Z ##[error]npm failed with error: C:\Program Files\nodejs\npm.cmd failed with return code: 1
2016-12-05T07:50:52.5577517Z ##[section]Finishing: npm test
2016-12-05T07:50:52.5577517Z ##[section]Starting: Post Job Cleanup
2016-12-05T07:50:52.5647514Z Cleaning any cached credential from repository: yonodejsx (Git)
2016-12-05T07:50:52.5697516Z ##[command]git remote set-url origin https://mcwdemo.visualstudio.com/_git/yonodejsx
2016-12-05T07:50:52.5917520Z ##[command]git remote set-url --push origin https://mcwdemo.visualstudio.com/_git/yonodejsx
2016-12-05T07:50:52.6117520Z ##[section]Finishing: Post Job Cleanup
2016-12-05T07:50:52.6117520Z ##[section]Finishing: Build

**Comment by DarqueWarrior** [comment]
I was able to duplicate. I am able to run on  my private agent but fails on hosted. I will see what dependency is missing.

**Comment by DarqueWarrior** [comment]
Issue corrected in 0.2.4.  If you have an existing project simply delete the uitest.js file and you can remove the selenium dependency from package.json and it will build.
