### ISSUE TITLE
Nodejs build problem

### ISSUE THREAD

**Issue by EduardoPiairoBc** [DarqueWarrior/generator-vsts#8]
I created a NodeJS with yo vsts.
I'm using a hosted agent and the build process breaks at npm test step.

Here's the log:
2016-12-06T08:37:08.6602646Z ##[section]Starting: npm test
2016-12-06T08:37:08.6612644Z ==============================================================================
2016-12-06T08:37:08.6612644Z Task         : npm
2016-12-06T08:37:08.6612644Z Description  : Run a npm command
2016-12-06T08:37:08.6612644Z Version      : 0.2.20
2016-12-06T08:37:08.6612644Z Author       : Microsoft Corporation
2016-12-06T08:37:08.6612644Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613746)
2016-12-06T08:37:08.6622630Z ==============================================================================
2016-12-06T08:37:08.9782650Z [command]C:\Program Files\nodejs\npm.cmd config list
2016-12-06T08:37:10.4382652Z ; cli configs
2016-12-06T08:37:10.4392644Z user-agent = "npm/3.8.6 node/v5.11.0 win32 x64"
2016-12-06T08:37:10.4392644Z 
2016-12-06T08:37:10.4392644Z ; environment configs
2016-12-06T08:37:10.4392644Z cache = "C:\\NPM\\Cache"
2016-12-06T08:37:10.4392644Z prefix = "C:\\NPM\\Modules"
2016-12-06T08:37:10.4392644Z 
2016-12-06T08:37:10.4392644Z ; globalconfig C:\NPM\Modules\etc\npmrc
2016-12-06T08:37:10.4392644Z registry = "http://registry.npmjs.org/"
2016-12-06T08:37:10.4392644Z 
2016-12-06T08:37:10.4392644Z ; builtin config undefined
2016-12-06T08:37:10.4392644Z 
2016-12-06T08:37:10.4392644Z ; node bin location = C:\Program Files\nodejs\node.exe
2016-12-06T08:37:10.4392644Z ; cwd = C:\a\1\s
2016-12-06T08:37:10.4392644Z ; HOME = C:\Users\buildguest
2016-12-06T08:37:10.4392644Z ; "npm config ls -l" to show all defaults.
2016-12-06T08:37:10.4392644Z 
2016-12-06T08:37:10.4582644Z [command]C:\Program Files\nodejs\npm.cmd test -- --grep unit*
2016-12-06T08:37:11.9672638Z 
2016-12-06T08:37:11.9672638Z > mynodejsdemo@0.0.0 test C:\a\1\s
2016-12-06T08:37:11.9672638Z > istanbul cover --report cobertura --report lcov node_modules/mocha/bin/_mocha -- -R xunit-file "--grep" "unit*"
2016-12-06T08:37:11.9672638Z 
2016-12-06T08:37:12.9532633Z No coverage information was collected, exit without writing coverage information
2016-12-06T08:37:12.9562649Z C:\a\1\s\node_modules\selenium-webdriver\index.js:115
2016-12-06T08:37:12.9562649Z   static createSession(...args) {}
2016-12-06T08:37:12.9572648Z                        ^^^
2016-12-06T08:37:12.9572648Z 
2016-12-06T08:37:12.9572648Z SyntaxError: Unexpected token ...
2016-12-06T08:37:12.9572648Z     at exports.runInThisContext (vm.js:53:16)
2016-12-06T08:37:12.9572648Z     at Module._compile (module.js:387:25)
2016-12-06T08:37:12.9572648Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-06T08:37:12.9582641Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-06T08:37:12.9582641Z     at Module.load (module.js:357:32)
2016-12-06T08:37:12.9582641Z     at Function.Module._load (module.js:314:12)
2016-12-06T08:37:12.9582641Z     at Module.require (module.js:367:17)
2016-12-06T08:37:12.9582641Z     at require (internal/module.js:20:19)
2016-12-06T08:37:12.9582641Z     at Object.<anonymous> (C:\a\1\s\test\uiTest.js:2:19)
2016-12-06T08:37:12.9582641Z     at Module._compile (module.js:413:34)
2016-12-06T08:37:12.9582641Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-06T08:37:12.9582641Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-06T08:37:12.9582641Z     at Module.load (module.js:357:32)
2016-12-06T08:37:12.9582641Z     at Function.Module._load (module.js:314:12)
2016-12-06T08:37:12.9582641Z     at Module.require (module.js:367:17)
2016-12-06T08:37:12.9582641Z     at require (internal/module.js:20:19)
2016-12-06T08:37:12.9582641Z     at C:\a\1\s\node_modules\mocha\lib\mocha.js:222:27
2016-12-06T08:37:12.9592631Z     at Array.forEach (native)
2016-12-06T08:37:12.9592631Z     at Mocha.loadFiles (C:\a\1\s\node_modules\mocha\lib\mocha.js:219:14)
2016-12-06T08:37:12.9592631Z     at Mocha.run (C:\a\1\s\node_modules\mocha\lib\mocha.js:487:10)
2016-12-06T08:37:12.9592631Z     at Object.<anonymous> (C:\a\1\s\node_modules\mocha\bin\_mocha:459:18)
2016-12-06T08:37:12.9592631Z     at Module._compile (module.js:413:34)
2016-12-06T08:37:12.9592631Z     at Object.Module._extensions..js (module.js:422:10)
2016-12-06T08:37:12.9592631Z     at Object.Module._extensions.(anonymous function) [as .js] (C:\a\1\s\node_modules\istanbul\lib\hook.js:109:37)
2016-12-06T08:37:12.9592631Z     at Module.load (module.js:357:32)
2016-12-06T08:37:12.9592631Z     at Function.Module._load (module.js:314:12)
2016-12-06T08:37:12.9592631Z     at Function.Module.runMain (module.js:447:10)
2016-12-06T08:37:12.9592631Z     at runFn (C:\a\1\s\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\lib\command\common\run-with-cover.js:251:17
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\lib\util\file-matcher.js:68:16
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:52:16
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:361:13
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:52:16
2016-12-06T08:37:12.9592631Z     at done (C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:246:17)
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:44:16
2016-12-06T08:37:12.9592631Z     at C:\a\1\s\node_modules\istanbul\node_modules\async\lib\async.js:358:17
2016-12-06T08:37:12.9592631Z     at LOOP (fs.js:1609:14)
2016-12-06T08:37:12.9592631Z     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-12-06T08:37:12.9592631Z     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-12-06T08:37:12.9772644Z npm ERR! Test failed.  See above for more details.
2016-12-06T08:37:13.0042648Z ##[error]npm failed with error: C:\Program Files\nodejs\npm.cmd failed with return code: 1
2016-12-06T08:37:13.0042648Z ##[section]Finishing: npm test

**Comment by DarqueWarrior** [comment]
Corrected in version 0.2.4.
